### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by songotag** [limpens/esp32-2432S028#1]
hello,

Thank you for your sharing

 I tested your code and it does not compile, what version of IDF are you using? I tested with IDF5.1.1

`Call Stack (most recent call first):
  C:/Espressif/frameworks/esp-idf-v5.1.1/tools/cmake/build.cmake:302 (__build_resolve_and_add_req)
  C:/Espressif/frameworks/esp-idf-v5.1.1/tools/cmake/build.cmake:595 (__build_expand_requirements)
  C:/Espressif/frameworks/esp-idf-v5.1.1/tools/cmake/project.cmake:547 (idf_build_process)
  CMakeLists.txt:7 (project)

-- Configuring incomplete, errors occurred!
See also "D:/esp32-8048S043-main/build/CMakeFiles/CMakeOutput.log".

 *  Arrêt du processus de terminal "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B d:\esp32-8048S043-main\build -S d:\esp32-8048S043-main". Code de sortie : 1. `

**Comment by limpens** [comment]
With esp-idf version 5.1.2, the build completes fine. Without the actual error you ran into, it is kinda hard to determine the issue.
